# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class History(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, subject_id: int=None, playbacks: int=None, start_date: datetime=None):  # noqa: E501
        """History - a model defined in Swagger

        :param id: The id of this History.  # noqa: E501
        :type id: int
        :param subject_id: The subject_id of this History.  # noqa: E501
        :type subject_id: int
        :param playbacks: The playbacks of this History.  # noqa: E501
        :type playbacks: int
        :param start_date: The start_date of this History.  # noqa: E501
        :type start_date: datetime
        """
        self.swagger_types = {
            'id': int,
            'subject_id': int,
            'playbacks': int,
            'start_date': datetime
        }

        self.attribute_map = {
            'id': 'id',
            'subject_id': 'subjectId',
            'playbacks': 'playbacks',
            'start_date': 'startDate'
        }
        self._id = id
        self._subject_id = subject_id
        self._playbacks = playbacks
        self._start_date = start_date

    @classmethod
    def from_dict(cls, dikt) -> 'History':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The History of this History.  # noqa: E501
        :rtype: History
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this History.

        User's identifier  # noqa: E501

        :return: The id of this History.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this History.

        User's identifier  # noqa: E501

        :param id: The id of this History.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def subject_id(self) -> int:
        """Gets the subject_id of this History.

        Identifier of the element (song or artist) in the history  # noqa: E501

        :return: The subject_id of this History.
        :rtype: int
        """
        return self._subject_id

    @subject_id.setter
    def subject_id(self, subject_id: int):
        """Sets the subject_id of this History.

        Identifier of the element (song or artist) in the history  # noqa: E501

        :param subject_id: The subject_id of this History.
        :type subject_id: int
        """
        if subject_id is None:
            raise ValueError("Invalid value for `subject_id`, must not be `None`")  # noqa: E501

        self._subject_id = subject_id

    @property
    def playbacks(self) -> int:
        """Gets the playbacks of this History.

        Number of playbacks of the element  # noqa: E501

        :return: The playbacks of this History.
        :rtype: int
        """
        return self._playbacks

    @playbacks.setter
    def playbacks(self, playbacks: int):
        """Sets the playbacks of this History.

        Number of playbacks of the element  # noqa: E501

        :param playbacks: The playbacks of this History.
        :type playbacks: int
        """
        if playbacks is None:
            raise ValueError("Invalid value for `playbacks`, must not be `None`")  # noqa: E501

        self._playbacks = playbacks

    @property
    def start_date(self) -> datetime:
        """Gets the start_date of this History.

        Start date and time of the record  # noqa: E501

        :return: The start_date of this History.
        :rtype: datetime
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date: datetime):
        """Sets the start_date of this History.

        Start date and time of the record  # noqa: E501

        :param start_date: The start_date of this History.
        :type start_date: datetime
        """
        if start_date is None:
            raise ValueError("Invalid value for `start_date`, must not be `None`")  # noqa: E501

        self._start_date = start_date
