# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SongMetrics(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, playbacks: int=None, sales: int=None, downloads: int=None):  # noqa: E501
        """SongMetrics - a model defined in Swagger

        :param id: The id of this SongMetrics.  # noqa: E501
        :type id: int
        :param playbacks: The playbacks of this SongMetrics.  # noqa: E501
        :type playbacks: int
        :param sales: The sales of this SongMetrics.  # noqa: E501
        :type sales: int
        :param downloads: The downloads of this SongMetrics.  # noqa: E501
        :type downloads: int
        """
        self.swagger_types = {
            'id': int,
            'playbacks': int,
            'sales': int,
            'downloads': int
        }

        self.attribute_map = {
            'id': 'id',
            'playbacks': 'playbacks',
            'sales': 'sales',
            'downloads': 'downloads'
        }
        self._id = id
        self._playbacks = playbacks
        self._sales = sales
        self._downloads = downloads

    @classmethod
    def from_dict(cls, dikt) -> 'SongMetrics':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SongMetrics of this SongMetrics.  # noqa: E501
        :rtype: SongMetrics
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this SongMetrics.

        Unique identifier of the song  # noqa: E501

        :return: The id of this SongMetrics.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this SongMetrics.

        Unique identifier of the song  # noqa: E501

        :param id: The id of this SongMetrics.
        :type id: int
        """

        self._id = id

    @property
    def playbacks(self) -> int:
        """Gets the playbacks of this SongMetrics.

        Total number of playbacks of the song  # noqa: E501

        :return: The playbacks of this SongMetrics.
        :rtype: int
        """
        return self._playbacks

    @playbacks.setter
    def playbacks(self, playbacks: int):
        """Sets the playbacks of this SongMetrics.

        Total number of playbacks of the song  # noqa: E501

        :param playbacks: The playbacks of this SongMetrics.
        :type playbacks: int
        """

        self._playbacks = playbacks

    @property
    def sales(self) -> int:
        """Gets the sales of this SongMetrics.

        Total number of sales of the song  # noqa: E501

        :return: The sales of this SongMetrics.
        :rtype: int
        """
        return self._sales

    @sales.setter
    def sales(self, sales: int):
        """Sets the sales of this SongMetrics.

        Total number of sales of the song  # noqa: E501

        :param sales: The sales of this SongMetrics.
        :type sales: int
        """

        self._sales = sales

    @property
    def downloads(self) -> int:
        """Gets the downloads of this SongMetrics.

        Total number of downloads of the song  # noqa: E501

        :return: The downloads of this SongMetrics.
        :rtype: int
        """
        return self._downloads

    @downloads.setter
    def downloads(self, downloads: int):
        """Sets the downloads of this SongMetrics.

        Total number of downloads of the song  # noqa: E501

        :param downloads: The downloads of this SongMetrics.
        :type downloads: int
        """

        self._downloads = downloads
