# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SongRecommendations(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, name: str=None, genre: str=None, image: str=None):  # noqa: E501
        """SongRecommendations - a model defined in Swagger

        :param id: The id of this SongRecommendations.  # noqa: E501
        :type id: int
        :param name: The name of this SongRecommendations.  # noqa: E501
        :type name: str
        :param genre: The genre of this SongRecommendations.  # noqa: E501
        :type genre: str
        :param image: The image of this SongRecommendations.  # noqa: E501
        :type image: str
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'genre': str,
            'image': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'genre': 'genre',
            'image': 'image'
        }
        self._id = id
        self._name = name
        self._genre = genre
        self._image = image

    @classmethod
    def from_dict(cls, dikt) -> 'SongRecommendations':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SongRecommendations of this SongRecommendations.  # noqa: E501
        :rtype: SongRecommendations
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this SongRecommendations.

        Unique identifier of the song  # noqa: E501

        :return: The id of this SongRecommendations.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this SongRecommendations.

        Unique identifier of the song  # noqa: E501

        :param id: The id of this SongRecommendations.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this SongRecommendations.

        Name of the song  # noqa: E501

        :return: The name of this SongRecommendations.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this SongRecommendations.

        Name of the song  # noqa: E501

        :param name: The name of this SongRecommendations.
        :type name: str
        """

        self._name = name

    @property
    def genre(self) -> str:
        """Gets the genre of this SongRecommendations.

        Musical genre of the song  # noqa: E501

        :return: The genre of this SongRecommendations.
        :rtype: str
        """
        return self._genre

    @genre.setter
    def genre(self, genre: str):
        """Sets the genre of this SongRecommendations.

        Musical genre of the song  # noqa: E501

        :param genre: The genre of this SongRecommendations.
        :type genre: str
        """

        self._genre = genre

    @property
    def image(self) -> str:
        """Gets the image of this SongRecommendations.

        URL of the song's cover image  # noqa: E501

        :return: The image of this SongRecommendations.
        :rtype: str
        """
        return self._image

    @image.setter
    def image(self, image: str):
        """Sets the image of this SongRecommendations.

        URL of the song's cover image  # noqa: E501

        :param image: The image of this SongRecommendations.
        :type image: str
        """

        self._image = image
