# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UserMetrics(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, listen_time: int=None, top_artist_id: int=None, top_song_id: int=None):  # noqa: E501
        """UserMetrics - a model defined in Swagger

        :param listen_time: The listen_time of this UserMetrics.  # noqa: E501
        :type listen_time: int
        :param top_artist_id: The top_artist_id of this UserMetrics.  # noqa: E501
        :type top_artist_id: int
        :param top_song_id: The top_song_id of this UserMetrics.  # noqa: E501
        :type top_song_id: int
        """
        self.swagger_types = {
            'listen_time': int,
            'top_artist_id': int,
            'top_song_id': int
        }

        self.attribute_map = {
            'listen_time': 'listenTime',
            'top_artist_id': 'topArtistId',
            'top_song_id': 'topSongId'
        }
        self._listen_time = listen_time
        self._top_artist_id = top_artist_id
        self._top_song_id = top_song_id

    @classmethod
    def from_dict(cls, dikt) -> 'UserMetrics':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserMetrics of this UserMetrics.  # noqa: E501
        :rtype: UserMetrics
        """
        return util.deserialize_model(dikt, cls)

    @property
    def listen_time(self) -> int:
        """Gets the listen_time of this UserMetrics.

        Total listening time of the user in minutes  # noqa: E501

        :return: The listen_time of this UserMetrics.
        :rtype: int
        """
        return self._listen_time

    @listen_time.setter
    def listen_time(self, listen_time: int):
        """Sets the listen_time of this UserMetrics.

        Total listening time of the user in minutes  # noqa: E501

        :param listen_time: The listen_time of this UserMetrics.
        :type listen_time: int
        """

        self._listen_time = listen_time

    @property
    def top_artist_id(self) -> int:
        """Gets the top_artist_id of this UserMetrics.

        Identifier of the most listened artist by the user  # noqa: E501

        :return: The top_artist_id of this UserMetrics.
        :rtype: int
        """
        return self._top_artist_id

    @top_artist_id.setter
    def top_artist_id(self, top_artist_id: int):
        """Sets the top_artist_id of this UserMetrics.

        Identifier of the most listened artist by the user  # noqa: E501

        :param top_artist_id: The top_artist_id of this UserMetrics.
        :type top_artist_id: int
        """

        self._top_artist_id = top_artist_id

    @property
    def top_song_id(self) -> int:
        """Gets the top_song_id of this UserMetrics.

        Identifier of the most listened song by the user  # noqa: E501

        :return: The top_song_id of this UserMetrics.
        :rtype: int
        """
        return self._top_song_id

    @top_song_id.setter
    def top_song_id(self, top_song_id: int):
        """Sets the top_song_id of this UserMetrics.

        Identifier of the most listened song by the user  # noqa: E501

        :param top_song_id: The top_song_id of this UserMetrics.
        :type top_song_id: int
        """

        self._top_song_id = top_song_id
