# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UserGenres(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, genre: str=None, count: int=None):  # noqa: E501
        """UserGenres - a model defined in Swagger

        :param id: The id of this UserGenres.  # noqa: E501
        :type id: int
        :param genre: The genre of this UserGenres.  # noqa: E501
        :type genre: str
        :param count: The count of this UserGenres.  # noqa: E501
        :type count: int
        """
        self.swagger_types = {
            'id': int,
            'genre': str,
            'count': int
        }

        self.attribute_map = {
            'id': 'id',
            'genre': 'genre',
            'count': 'count'
        }
        self._id = id
        self._genre = genre
        self._count = count

    @classmethod
    def from_dict(cls, dikt) -> 'UserGenres':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserGenres of this UserGenres.  # noqa: E501
        :rtype: UserGenres
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this UserGenres.

        Unique identifier of the genre record  # noqa: E501

        :return: The id of this UserGenres.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this UserGenres.

        Unique identifier of the genre record  # noqa: E501

        :param id: The id of this UserGenres.
        :type id: int
        """

        self._id = id

    @property
    def genre(self) -> str:
        """Gets the genre of this UserGenres.

        Name of the musical genre  # noqa: E501

        :return: The genre of this UserGenres.
        :rtype: str
        """
        return self._genre

    @genre.setter
    def genre(self, genre: str):
        """Sets the genre of this UserGenres.

        Name of the musical genre  # noqa: E501

        :param genre: The genre of this UserGenres.
        :type genre: str
        """

        self._genre = genre

    @property
    def count(self) -> int:
        """Gets the count of this UserGenres.

        Number of songs listened to of this genre  # noqa: E501

        :return: The count of this UserGenres.
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count: int):
        """Sets the count of this UserGenres.

        Number of songs listened to of this genre  # noqa: E501

        :param count: The count of this UserGenres.
        :type count: int
        """

        self._count = count
